# Generated by Django 3.2 on 2021-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
