# Generated by Django 3.2 on 2021-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todo_list_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='date',
            field=models.DateField(default='1997-01-22'),
            preserve_default=False,
        ),
    ]
